-- =============================================================================
-- 0004_demo_flag — separating invented rows from real patients
-- =============================================================================
-- The panel's charts are unreadable against the live table: two appointments,
-- no messages, one testimonial. A clinic looking at that cannot tell a working
-- dashboard from a broken one, so the charts need demo rows to render against.
--
-- Demo rows in an appointment book are dangerous in a way demo rows in most
-- applications are not. The failure is concrete and it is one phone call long:
-- a receptionist opens the queue on Monday, reads a name and a number that a
-- script invented, and rings a person who does not exist — or worse, rings
-- whoever really owns that number. A demo row that cannot be distinguished from
-- a real one is not test data, it is a fabricated patient record.
--
-- This column is the distinction. Three properties matter and all three come
-- from the definition below:
--
--   NOT NULL     — a row is demo or it is not; there is no third state for the
--                  UI or the purge to guess at.
--   DEFAULT false — every row that already exists, and every appointment a
--                  patient submits from now on, is real and unflagged without
--                  any code being changed. src/app/actions.ts never mentions
--                  this column, so it cannot accidentally set it.
--   boolean      — `DELETE ... WHERE is_demo` is exact. It cannot match a real
--                  row, and there is no pattern, prefix or date range for the
--                  purge to get subtly wrong.
--
-- Adding a NOT NULL column with a constant default has been metadata-only since
-- Postgres 11: the default is recorded in the catalog and existing rows are
-- filled in as they are next written. No rewrite, no long ACCESS EXCLUSIVE lock
-- on a table the public appointment form is inserting into.
--
-- Column-level grants are not in play here — 0002 granted CRUD on whole tables
-- to vd_app — so a new column needs no new GRANT to be readable and writable by
-- the application.
-- =============================================================================

ALTER TABLE app.appointments
  ADD COLUMN IF NOT EXISTS is_demo boolean NOT NULL DEFAULT false;
ALTER TABLE app.contact_messages
  ADD COLUMN IF NOT EXISTS is_demo boolean NOT NULL DEFAULT false;
ALTER TABLE app.testimonials
  ADD COLUMN IF NOT EXISTS is_demo boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN app.appointments.is_demo IS
  'Generated by src/scripts/demo-data.ts, not submitted by a patient. Never call the number on one of these rows. Remove with: npm run db:demo:purge';
COMMENT ON COLUMN app.contact_messages.is_demo IS
  'Generated by src/scripts/demo-data.ts, not sent by a person. Remove with: npm run db:demo:purge';
COMMENT ON COLUMN app.testimonials.is_demo IS
  'Generated by src/scripts/demo-data.ts. Never approve one of these: an approved testimonial is published on the public homepage under an invented patient name.';

-- -----------------------------------------------------------------------------
-- Partial indexes — on the demo side, and only on the two big tables
-- -----------------------------------------------------------------------------
-- The predicate indexes the rows that are meant to be temporary, which reads
-- backwards until you look at the steady state. Once the demo set is purged the
-- index holds nothing at all, and that is exactly when it earns its place: the
-- panel's "this dashboard is showing demo data" check runs on every dashboard
-- render, and against a clean production table it is answered from an empty
-- index instead of scanning an appointment book that only grows.
--
-- While the demo set IS loaded the planner will ignore it and scan — several
-- hundred of a few hundred rows match, so an index is the slower plan and
-- Postgres knows it. That costs nothing: the purge runs once, by hand.
--
-- app.testimonials deliberately gets no such index. It holds a handful of rows
-- and is designed to stay small; a sequential scan there is a single page read,
-- which is cheaper than the write amplification an extra index puts on every
-- moderation decision.
CREATE INDEX IF NOT EXISTS appointments_demo_idx
  ON app.appointments (submitted_at DESC) WHERE is_demo;
CREATE INDEX IF NOT EXISTS contact_messages_demo_idx
  ON app.contact_messages (submitted_at DESC) WHERE is_demo;
